/*******************************************************************************
 * Copyright (c) 2011 University of Southampton.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package ac.soton.eventb.emf.core.extension.navigator.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryContentProvider;
import org.eclipse.emf.workspace.util.WorkspaceSynchronizer;
import org.eclipse.jface.viewers.Viewer;
import org.eclipse.ui.IMemento;
import org.eclipse.ui.navigator.ICommonContentExtensionSite;
import org.eclipse.ui.navigator.ICommonContentProvider;
import org.eventb.core.IContextRoot;
import org.eventb.core.IEventBRoot;
import org.eventb.core.IMachineRoot;
import org.eventb.emf.core.EventBElement;
import org.eventb.emf.persistence.EMFRodinDB;

import ac.soton.eventb.emf.core.extension.navigator.ExtensionNavigatorPlugin;

/**
 * Event-B EMF extension content provider for the IEventBRoot elements.
 * Provides the content of AbstractExtensions of a root element.
 * A slightly modified copy of the content providers generated by GMF for diagram elements.
 * 
 * cfs 11/03/14 - Modified to use new EMFRodinDB for loading
 * cfs 04/15 - do not set read only resource map as may be edited by navigator commands
 * 
 * @author vitaly
 *
 */
public class ExtensionContentProvider implements ICommonContentProvider {

	protected AdapterFactoryContentProvider myAdapterFactoryContentProvier;

	protected static final Object[] EMPTY_ARRAY = new Object[0];
	
	/**
	 * Create an EMFRodinDB for loading extensions into EMF
	 */
	private final static EMFRodinDB emfRodinDB = new EMFRodinDB();
	

	private Viewer myViewer;

	private WorkspaceSynchronizer myWorkspaceSynchronizer;

	private Runnable myViewerRefreshRunnable;

	/**
	 * Constructor
	 */
	public ExtensionContentProvider() {
		myAdapterFactoryContentProvier = new AdapterFactoryContentProvider(ExtensionNavigatorPlugin.getDefault().getItemProvidersAdapterFactory());
		
		//This used to set the resource as read only but this caused problems because..
		//  the resource may be changed by various navigator commands that also use this editing domain and resource set.
		
//		((AdapterFactoryEditingDomain) editingDomain).setResourceToReadOnlyMap(new HashMap() {
//																					public Object get(Object key) {
//																						if (!containsKey(key)) {
//																							put(key, Boolean.TRUE);
//																						}
//																						return super.get(key);
//																					}
//																				});
		
		myViewerRefreshRunnable = new Runnable() {
			public void run() {
				if (myViewer != null) {
					myViewer.refresh();
				}
			}
		};
		myWorkspaceSynchronizer = new WorkspaceSynchronizer( emfRodinDB.getEditingDomain(),
				new WorkspaceSynchronizer.Delegate() {
					public void dispose() {
					}

					public boolean handleResourceChanged(final Resource resource) {
						resource.eSetDeliver(false);
						resource.unload();
						resource.eSetDeliver(true);
						asyncRefresh();
						return true;
					}

					public boolean handleResourceDeleted(Resource resource) {
						resource.eSetDeliver(false);
						resource.unload();
						resource.eSetDeliver(true);
						asyncRefresh();
						return true;
					}

					public boolean handleResourceMoved(Resource resource,
							final URI newURI) {
						resource.eSetDeliver(false);
						resource.unload();
						resource.eSetDeliver(true);
						asyncRefresh();
						return true;
					}
				});
	}

	@Override
	public Object[] getElements(Object inputElement) {
		return getChildren(inputElement);
	}

	@Override
	public Object[] getChildren(Object parentElement) {
		if (parentElement instanceof IMachineRoot || parentElement instanceof IContextRoot) {
			IEventBRoot root = (IEventBRoot) parentElement;
			EventBElement element = emfRodinDB.loadEventBComponent(root);
			if (element != null){
				return wrapEObjects(
						element.getExtensions().toArray(),
						parentElement);
			}	
		}
		
		if (parentElement instanceof ExtensionNavigatorItem) {
			return wrapEObjects(
					myAdapterFactoryContentProvier.getChildren(((ExtensionNavigatorItem) parentElement)
							.getEObject()), parentElement);
		}
		return EMPTY_ARRAY;
	}

	public Object[] wrapEObjects(Object[] objects, Object parentElement) {
		Collection<ExtensionNavigatorItem> result = new ArrayList<ExtensionNavigatorItem>();
		for (int i = 0; i < objects.length; i++) {
			if (objects[i] instanceof EObject) {
				result.add(new ExtensionNavigatorItem(
						(EObject) objects[i], parentElement,
						myAdapterFactoryContentProvier));
			}
		}
		return result.toArray();
	}

	@Override
	public Object getParent(Object element) {
		if (element instanceof ExtensionNavigatorItem) {
			ExtensionNavigatorItem navigatorItem = (ExtensionNavigatorItem) element;
			return navigatorItem.getParent();
		}
		return null;
	}

	@Override
	public boolean hasChildren(Object element) {
		return getChildren(element).length > 0;
	}

	@Override
	public void dispose() {
		myWorkspaceSynchronizer.dispose();
		myWorkspaceSynchronizer = null;
		myViewerRefreshRunnable = null;
		myViewer = null;
		//editingDomain.dispose();		do not dispose as we are using the EMFRodinDB editing domain
	}

	void asyncRefresh() {
		if (myViewer != null && !myViewer.getControl().isDisposed()) {
			myViewer.getControl().getDisplay()
					.asyncExec(myViewerRefreshRunnable);
		}
	}

	@Override
	public void inputChanged(Viewer viewer, Object oldInput, Object newInput) {
		myViewer = viewer;
	}

	@Override
	public void restoreState(IMemento aMemento) {
		/* not implemented */
	}

	@Override
	public void saveState(IMemento aMemento) {
		/* not implemented */
	}

	@Override
	public void init(ICommonContentExtensionSite aConfig) {
		/* not implemented */
	}

}
